---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true
services:
  - docker
# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install docker-py
  - pip install molecule

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  # - ansible-galaxy install AAROC.certificates
  # - ansible-playbook -c local tests/test.yml -i tests/inventory --syntax-check
  # - ansible-playbook -c local tests/test.yml -i tests/inventory
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
