---
# tasks file for AAROC.certificates
- block:
    - name: YUM repo for TrustAnchors
      get_url:
        url: "http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo"
        dest: /etc/yum.repos.d/egi-trustanchors.repo
      tags:
        - repos
        - IGTF
        - download

    - name: EGI trustanchors present
      yum:
        name: "{{ igtf_repo_url }}/{{ igtf_release_name }}-{{ igtf_release_version }}.noarch.rpm"
        state: present
      tags:
        - repos
        - IGTF
        - download
  when: ansible_os_family == 'RedHat'

- block:
    - name: Add EUGridPMA key
      apt_key:
        url: https://dist.eugridpma.info/distribution/igtf/current/GPG-KEY-EUGridPMA-RPM-3
        state: present
      tags:
        - repos
        - IGTF
        - download

    - name: Ensure  that the EUGridPMA repo is in source.list
      blockinfile:
        dest: /etc/apt/sources.list
        block: >
            #### EGI Trust Anchor Distribution ####

            deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core
        state: present
      tags:
        - repos
        - IGTF

    - name: EGI trustanchors present
      apt:
        update_cache: true
        name: ca-policy-egi-core
        state: present
      retries: 2
    # should have a when file state==abset here
      tags:
        - repos
        - IGTF
        - download
  when: ansible_os_family == 'Debian'


- name: Create /etc/grid-security directory
  file:
    path: /etc/grid-security/certificates
    owner: root
    group: root
    mode: 775
    state: directory
    force: true
  tags:
    - certificates

- name: Copy host x509 certificate into /etc/grid-security
  copy:
    src: "etc/grid-security/hostcert.pem-{{ ansible_fqdn }}"
    dest: /etc/grid-security/hostcert.pem
    owner: root
    group: root
    mode: 0644
    force: true
  when:  needs_certificate == 'true'
  tags:
    - certificates

- name: Copy host x509 private key into /etc/grid-security
  copy:
    src: "etc/grid-security/hostkey.pem-{{ ansible_fqdn }}"
    dest: /etc/grid-security/hostkey.pem
    owner: root
    group: root
    mode: 0400
  when: needs_certificate == 'true'
  tags:
    - certificates

# - name: Copy over CA certs by hand
#   copy:
#     src: "etc/grid-security/certificates/{{ item }}"
#     dest: "/etc/grid-security/certificates/{{ item }}"
#   with_items:
#     - 16b5ebeb.0
#     - 16b5ebeb.crl_url
#     - 16b5ebeb.r0
#     - 16b5ebeb.signing_policy
#     - 8c65b6c6.0
#     - 8c65b6c6.crl_url
#     - 8c65b6c6.r0
#     - 8c65b6c6.signing_policy
#     - AAROC.0
#     - AAROC.crl_url
#     - AAROC.r0
#     - AAROC.signing_policy
#   tags:
#     - certificates
#
# - name: Add SAGrid VO certs and LSC files
#   copy:
#     src: etc/grid-security/vomsdir
#     dest: /etc/grid-security/
#     owner: root
#     group: root
